control_sindical/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.log_in, name="login"),
    path('logout/', views.log_out, name="logout"), 
    path('sindicato/', views.sindicato, name="sindicato"),
    path('datos_sindicato/<int:id>', views.datos_sindicato, name="datos_sindicato"),
    path('detalles_trabajador/<int:id>', views.detalles_trabajador, name="detalles_trabajador"),
    path('trabajadores/', views.trabajadores, name="trabajadores"),
    path('map/', views.mapt, name="map"),
    path('asambleas/', views.asambleas, name="asambleas"),
]

gestion_info_SEPR/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('control_sindical.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

control_sindical/models.py
from django.db import models
from datetime import date
from django.db.models.signals import post_save, pre_delete, pre_save
from django.dispatch import receiver
import os

# Create your models here.
class Sindicato(models.Model):
    nombre = models.CharField(max_length=100, blank=False, null=False)
    dirección = models.CharField(max_length=100, blank=False, null=False)

    def __str__(self):
        return self.nombre

    
class Trabajador(models.Model):
    nombre = models.CharField(max_length=20, blank=False, null=False)
    apellido = models.CharField(max_length=30, blank=False, null=False)
    ci = models.IntegerField(blank=False, null=False)
    salario_mensual = models.FloatField(blank=False, null=False)
    cuota = models.FloatField(blank=False, null=False)
    fecha_alta = models.DateField(default=date.today, blank=False, null=False)
    fecha_baja = models.DateField(blank=True, null=True)
    sindicato = models.ForeignKey(Sindicato, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre
    
class Map(models.Model):
    monto = models.FloatField(blank=False, null=False)
    fecha_pago = models.DateField(blank=False, null=False)
    trabajador = models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    pagado = models.BooleanField(default=False)

    def __str__(self):
        txt = "Trabajador: {}, Fecha de pago: {}, Monto: {}"
        return txt.format(self.trabajador, self.fecha_pago, self.monto)
    
class AsambleaAfiliados(models.Model):
    fecha = models.DateField(default=date.today, blank=False, null=False)
    cantidad_trabajadores = models.IntegerField(blank=False, null=False)
    cantidad_acuerdos = models.IntegerField(blank=False, null=False)
    sindicato = models.ForeignKey(Sindicato, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='imagenes_asamblea/', null=True, blank=True, default='path/media/default_image.jpg')

    def __str__(self):
        txt = "Sindicato: {}, Cantidad de acuerdos: {}, Fecha: {}"
        return txt.format(self.sindicato, self.cantidad_acuerdos, self.fecha)



#----------------------------------------------------------------------------

@receiver(pre_delete, sender=AsambleaAfiliados)
def eliminar_imagen_de_asamblea(sender, instance, **kwargs):
    # Verificar si el área tiene una imagen asociada y eliminarla
    if instance.imagen:
        if os.path.isfile(instance.imagen.path):
            os.remove(instance.imagen.path)

@receiver(pre_save, sender=AsambleaAfiliados)
def eliminar_imagen_anterior_al_actualizar(sender, instance, **kwargs):
    if not instance.pk:  # El área es nueva, no hay imagen anterior que eliminar
        return False

    try:
        asamblea_anterior = AsambleaAfiliados.objects.get(pk=instance.pk)  # Obtener el área anterior de la base de datos
    except AsambleaAfiliados.DoesNotExist:
        return False  # El área anterior no existe, no hay imagen anterior que eliminar

    if asamblea_anterior.imagen:  # Verificar si el área anterior tiene una imagen
        nueva_imagen = instance.imagen
        if asamblea_anterior.imagen != nueva_imagen:  # Verificar si se ha seleccionado una nueva imagen
            if os.path.isfile(asamblea_anterior.imagen.path):  # Verificar si el archivo de imagen existe en el sistema de archivos
                os.remove(asamblea_anterior.imagen.path)                

control_sindical/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Sindicato, Trabajador, Map, AsambleaAfiliados


# Create your views here.
@login_required
def index(request):
    return render(request, 'control_sindical/index.html', {})

def log_in(request):
    if request.method =='GET':
        return render(request, 'control_sindical/login.html', {'form': AuthenticationForm})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.success(request, "El usuario no existe, o la password es incorrecta")
            return render(request, 'control_sindical/login.html', {'form': AuthenticationForm})
        else:
            login(request, user)
            return redirect('index')
        
@login_required
def log_out(request):
    logout(request)
    return redirect('index')  

@login_required
def sindicato(request):
    sindicatos = Sindicato.objects.filter(nombre__icontains=request.GET.get('search', ''))
    cantidad = len(sindicatos)
    context = {
        'sindicatos': sindicatos,
        'cantidad': cantidad,
    }
    return render(request, 'control_sindical/sindicatos.html', context)

@login_required
def datos_sindicato(request, id):
    sindicato = get_object_or_404(Sindicato, id=id)
    trabajadores = Trabajador.objects.filter(nombre__icontains=request.GET.get('search', ''), sindicato=sindicato)
    context = {
        'sindicato': sindicato,
        'trabajadores': trabajadores,
    }
    return render(request, 'control_sindical/datos_sindicatos.html', context)


@login_required
def detalles_trabajador(request, id):
    trabajador = get_object_or_404(Trabajador, id=id)
    context = {
        'trabajador': trabajador
    }
    return render(request, 'control_sindical/detalles_trabajador.html', context)

@login_required
def trabajadores(request):
    trabajadores = Trabajador.objects.filter(nombre__icontains=request.GET.get('search', ''))
    context = {
        'trabajadores': trabajadores,
    }
    return render(request, 'control_sindical/trabajadores.html', context)




def mapt(request):
    # Obtén los valores de búsqueda de los parámetros GET (si existen)
    search = request.GET.get('search', '')
    mes = request.GET.get('mes', '')
    anio = request.GET.get('anio', '')

    # Filtra a los trabajadores en función de la búsqueda
    trabajadores = Trabajador.objects.all()
    
    if search:
        trabajadores = trabajadores.filter(nombre__icontains=search)

    # Puedes filtrar por mes y año si están presentes
    if mes:
        trabajadores = trabajadores.filter(map__fecha_pago__month=mes)

    if anio:
        trabajadores = trabajadores.filter(map__fecha_pago__year=anio)

    context = {
        'trabajadores': trabajadores,
        'meses': range(1, 13),  # Meses del 1 al 12
        'anios': range(2020, 2031)  # Años del 2020 al 2030
    }

    return render(request, 'control_sindical/map.html', context)



@login_required
def asambleas(request):
    nombre_sindicato = request.GET.get('search', '')
    asambleas = AsambleaAfiliados.objects.filter(sindicato__nombre__icontains=nombre_sindicato).order_by('-fecha')
    context = {
        'asambleas': asambleas,
    }
    return render(request, 'control_sindical/asambleas.html', context)

templates/control_sindical/asambleas.html
{% extends "layout/base.html" %}

{% block 'title'%} Asambleas {% endblock %}

{% block search %}
    <form class="d-flex" role="search" action="" method='GET'>
        <input class="form-control me-2" type="search" name="search" placeholder="Nombre del Sindicato" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Buscar</button>
    </form>
{% endblock search %}


{% block breadcrumb %}
    <div class="container p-1 d-flex">
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "asambleas" %}">Asambleas</a></li>
    <div>
{% endblock  %}

{% block 'content' %}
<table class="table table-striped mt-3">
    <thead>
        <tr>
            <th scope="col">sindicato</th>
            <th scope="col">Fecha</th>
            <th scope="col">Cantidad de trabajadores</th>
            <th scope="col">cantidad de acuerdos</td>
            <th scope="col">Imagen del acta</td>
        </tr>
    </thead>
    <tbody>
        {% for asamblea in asambleas %}
            <tr>
                <td>{{ asamblea.sindicato }}</td>
                <td>{{ asamblea.fecha }}</td>
                <td>{{ asamblea.cantidad_trabajadores }}</td>
                <td>{{ asamblea.cantidad_acuerdos }}</td>
                <td>
                    <button type="button" class="btn btn-secondary btn-sm btn-login" data-bs-toggle="modal" data-bs-target="#exampleModal{{ asamblea.id }}1">
                        Imagen <i class="bi bi-image"></i>
                    </button>
                    <div class="modal fade" id="exampleModal{{ asamblea.id }}1" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-xl">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Imagen</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <img src="{{ asamblea.imagen.url }}" class="img-fluid" alt="Imagen">
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table> 
{% endblock %}

templates/control_sindical/datos_sindicatos.html
{% extends "layout/base.html" %}

{% block 'title'%} DAtos de Sindicatos {% endblock %}

{% block search %}
    <form class="d-flex" role="search" action="" method='GET'>
        <input class="form-control me-2" type="search" name="search" placeholder="Nombre del Sindicato" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Buscar</button>
    </form>
{% endblock search %}


{% block breadcrumb %}
    <div class="container p-1 d-flex">
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "sindicato" %}">Sindicato</a></li>
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "datos_sindicato" id=sindicato.id %}">Datos del Sindicato</a></li>
    <div>
{% endblock  %}
    
{% block 'content' %}
    <div class="container">
        <h2 class="text-center mt-3">{{ sindicato.nombre }}</h2>
        
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">Apellidos</th>
                <th scope="col">CI</th>
                <th scope="col">Salario Mensual</th>
                <th scope="col">Cuaota</th>
                <th scope="col">Fecha de alta</th>
                <th scope="col">Fecha de baja</th>
            </tr>
        </thead>
        <tbody>
            {% for trabajador in trabajadores %}
                <tr>
                    <td><a class="text-dark" href="{% url "detalles_trabajador" id=trabajador.id %}">{{ trabajador.nombre }}</a></td>
                    <td>{{ trabajador.apellido }}</td>
                    <td>{{ trabajador.ci }}</td>
                    <td>{{ trabajador.salario_mensual }}</td>
                    <td>{{ trabajador.cuota }}</td>
                    <td>{{ trabajador.fecha_alta }}</td>
                    <td>{% if trabajador.fecha_baja == None %}Activo 
                        {% else %}{{ trabajador.fecha_baja }}
                        {% endif %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/control_sindical/detalles_trabajador.html
{% extends "layout/base.html" %}

{% block 'title'%} Detalles del trabajador {% endblock %}


{% block breadcrumb %}
    <div class="container p-1 d-flex">
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "sindicato" %}">Sindicato</a></li>
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "datos_sindicato" id=trabajador.sindicato.id %}">Datos del Sindicato</a></li>
        <li class="breadcrumb-item"><a class="text-secondary"href="">Trabajador</a></li>
    <div>
{% endblock  %}


{% block 'content' %}
    <div class="d-flex justify-content-center">
        <div class="mt-4 p-3 d-inline-block caja-trabajador shadow rounded">
            <p><b>Nombre:</b> {{ trabajador.nombre }}</p>
            <p><b>Apellido:</b> {{ trabajador.apellido }}</p>
            <p><b>Ci:</b> {{ trabajador.ci }}</p>
            <p><b>Salario mensual:</b> {{ trabajador.salario_mensual }}</p>
            <p><b>Cuota:</b> {{ trabajador.cuota }}</p>
            <p><b>Fecha alta:</b> {{ trabajador.fecha_alta }}</p>
            <p><b>Fecha baja:</b> {% if trabajador.fecha_baja == None %}Activo 
                                    {% else %}{{ trabajador.fecha_baja }}
                                    {% endif %}</p>
            <p><b>Sindicato:</b> {{ trabajador.sindicato }}</p>
            <p>{% with map_data=trabajador.map_set.first %}
                {% if map_data %}
                    <p><b>Fecha de Map:</b> {{ map_data.fecha_pago }}, <b>Monto:</b> {{ map_data.monto }}</p>
                {% else %}
                    <p>No hay datos de Map para este trabajador</p>
                {% endif %}
            {% endwith %}</td></p>
        </div>
    </div>
{% endblock %}

templates/control_sindical/index.html
{% extends "layout/base.html" %}

{% block 'title'%} Home {% endblock %}

{% block search %}
    <form class="d-flex" role="search" action="" method='GET'>
        <input class="form-control me-2" type="search" name="search" placeholder="Nombre del Sindicato" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Buscar</button>
    </form>
{% endblock search %}

{% block breadcrumb %}
    
{% endblock  %}


{% block 'content' %}
    <div class="container text-center pt-5">
        <p class="fs-5">El Sindicato Nacional de Energía y Minas, conocido anteriormente como el Sindicato Nacional de las Industrias, Química, la Minería y la Energética, fue fundado el día 3 de febrero de 1981, a partir de la necesidad de los trabajadores cubanos de unificarse en la defensa de sus intereses y bajo el principio de organización ramal. A él se subordinan los burós provinciales, a los cuales a su vez se le subordinan los burós municipales y extraterritoriales.</p>
        <p class="fs-5">El Sindicato Nacional de Energía y Minas cuenta con alrededor de 91  mil afiliados, agrupados en secciones sindicales. En la provincia de Pinar de Rio se cuenta con 4119 afiliados, de ellos 69 no estatales y 235 jubilados, 112  secciones sindicales, 7 burós de centros de trabajo y 2  buós extraterritoriales.</p>
        <p class="fs-5">El Buró Extraterritorial de la Empresa Eléctrica de Pinar del Río se crea una vez fundada dicha institución el 23 de febrero de 2001, a través de la resolución No.70 dictada por quien fuera Ministro de la Industria Básica, subordinada a la Unión Eléctrica perteneciente al actual Ministerio de Energía y Minas, con el Objetivo de agrupar y organizar a los  trabajadores, educarlos, prepararlos, representarlos y movilizaros en el cumplimiento de la actividad laboral y  social  del país y además de defenderlos  ante  el  estado, la sociedad y los empleadores en una relación constructiva y exigente por ambas partes.</p>
        <p class="fs-5">El Buró Extraterritorial está integrado por un total de 1571 trabajadores distribuidos 32  secciones sindicales y 10 delegados, pertenecientes a las Unidades Empresariales de Base UEB subordinados a las empresas que se encuentran distribuidas en 11 municipios de la provincia Pinar del Río.</p>
    </div>
{% endblock %}

templates/control_sindical/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Compañía de Diseño Web">
    <meta name="keywords" content="Diseño web, pagina web, crear sitio web, una web">
    <meta name="copyright" content="T3D Design Company">
    <meta name="author" content="David A. Chentes">
    <meta name="audience" content="all">
    <meta name="description" content="Empresa de desarrollo y tecnologías web, una buena opción para todo el interesado en su presencia en línea">
    <meta name="robots" content="index, all, follow">
    <meta name="category" content="Diseño Web">  
    <meta name="telephone" content="+1 224 288 1535">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="" type="image/png" sizes="16x16">
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/forms.css" %}">
</head>

<body class="prueba d-flex justify-content-center align-items-center" id="page-top">
    

    
    <div class="d-flex justify-content-center align-items-center">
        <form  class="p-5 rounded-3 text-light sombra-login" actions="{% url "login" %}" method="POST">
            {% csrf_token %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-primary alerta text-center" role="alert"{% endif %}>{{ message }}</div>
                {% endfor %}
            </ul>
            {% endif %}
            <h3 class="text-center mt-0 mb-4 text-login">GISEP</h3>
            {{form.as_p}}
        
            <input class="btn btn-login" type="submit" value="Submit">
        </form>
    </div>
    
    <script src="{% static "js/main.js" %}"></script>
</body>
</html>

templates/control_sindical/map.html
{% extends "layout/base.html" %}

{% block 'title'%} MAP {% endblock %}

{% block search %}
<form class="d-flex" role="search" action="" method="GET">
    <!-- Campo de búsqueda por nombre del trabajador -->
    <input class="form-control me-2" type="search" name="search" placeholder="Trabajador" aria-label="Search" value="{{ request.GET.search }}">
    
    <!-- Filtro por mes -->
    <select class="form-control me-2" name="mes">
        <option value="">Mes</option>
        {% for i in meses %}
            <option value="{{ i }}" {% if request.GET.mes == i|stringformat:"d" %}selected{% endif %}>{{ i }}</option>
        {% endfor %}
    </select>

    <!-- Filtro por año -->
    <select class="form-control me-2" name="anio">
        <option value="">Año</option>
        {% for i in anios %}
            <option value="{{ i }}" {% if request.GET.anio == i|stringformat:"d" %}selected{% endif %}>{{ i }}</option>
        {% endfor %}
    </select>

    <button class="btn btn-outline-dark" type="submit">Buscar</button>
</form>
{% endblock search %}


{% block breadcrumb %}
    <div class="container p-1 d-flex">
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "map" %}">MAP</a></li>
    <div>
{% endblock  %}

{% block 'content' %}
<table class="table table-striped mt-3">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Sindicato</th>
            <th scope="col">Fecha de pago y Monto</td>
            <th scope="col">Pagado</td>
        </tr>
    </thead>
    <tbody>
        {% for trabajador in trabajadores %}
            <tr>
                <td><a class="text-dark" href="{% url "detalles_trabajador" id=trabajador.id %}">{{ trabajador.nombre }}</a></td>
                <td>{{ trabajador.apellido }}</td>
                <td>{{ trabajador.sindicato }}</td>
                <td>
                    {% with map_data=trabajador.map_set.first %}
                        {% if map_data %}
                            <p>Fecha de pago: {{ map_data.fecha_pago }}, Monto: {{ map_data.monto }}</p>
                        {% else %}
                            <p>No hay datos de Map para este trabajador</p>
                        {% endif %}
                    {% endwith %}
                </td>
                <td>
                    {% with map_data=trabajador.map_set.first %}
                        {% if map_data %}
                            {% if map_data.pagado is True %}
                                <p class="text-success">Pago efectuado</p>
                            {% else %}
                                <p class="text-danger">Pago pendiente</p>
                            {% endif %}
                        {% else %}
                            <p>---</p>
                        {% endif %}
                    {% endwith %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/control_sindical/sindicatos.html
{% extends "layout/base.html" %}

{% block 'title'%} Sindicato {% endblock %}

{% block search %}
    <form class="d-flex" role="search" action="" method='GET'>
        <input class="form-control me-2" type="search" name="search" placeholder="Nombre del Sindicato" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Buscar</button>
    </form>
{% endblock search %}


{% block breadcrumb %}
    <div class="container p-1 d-flex">
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "sindicato" %}">Sindicato</a></li>
    <div>
{% endblock  %}

{% block 'content' %}
    <h5 class="text-center mt-4">Cantidad de sindicatos "{{ cantidad }}"</h5>
    <div class="container mt-2 row d-flex justify-content-center align-item-center ms-auto me-auto">
        {% for sindicato in sindicatos %}    
            <div class="card text-center m-3 bg-body-tertiary rounded shadow col-3" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ sindicato.nombre }}</h5>
                    <p class="card-text">{{ sindicato.dirección }}</p>
                    <a href="{% url "datos_sindicato" id=sindicato.id %}" class="btn btn-login">Ver detalles</a>
                </div>
            </div>
        {% endfor %}
    </div>    
{% endblock %}

templates/control_sindical/trabajadores.html
{% extends "layout/base.html" %}

{% block 'title'%} Trabajadores {% endblock %}

{% block search %}
    <form class="d-flex" role="search" action="" method='GET'>
        <input class="form-control me-2" type="search" name="search" placeholder="Nombre del trabajador" aria-label="Search">
        <button class="btn btn-outline-dark" type="submit">Buscar</button>
    </form>
{% endblock search %}


{% block breadcrumb %}
    <div class="container p-1 d-flex">
        <li class="breadcrumb-item"><a class="text-secondary"href="{% url "trabajadores" %}">Trabajadores</a></li>
    <div>
{% endblock  %}

{% block 'content' %}
<table class="table table-striped mt-3">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">CI</th>
            <th scope="col">Sindicato</th>
            <th scope="col">Salario Mensual</th>
            <th scope="col">Cuaota</th>
            <th scope="col">Fecha de alta</th>
            <th scope="col">Fecha de baja</th>
        </tr>
    </thead>
    <tbody>
        {% for trabajador in trabajadores %}
            <tr>
                <td><a class="text-dark" href="{% url "detalles_trabajador" id=trabajador.id %}">{{ trabajador.nombre }}</a></td>
                <td>{{ trabajador.apellido }}</td>
                <td>{{ trabajador.ci }}</td>
                <td>{{ trabajador.sindicato }}</td>
                <td>{{ trabajador.salario_mensual }}</td>
                <td>{{ trabajador.cuota }}</td>
                <td>{{ trabajador.fecha_alta }}</td>
                <td>{% if trabajador.fecha_baja == None %}Activo 
                    {% else %}{{ trabajador.fecha_baja }}
                    {% endif %}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Compañía de Diseño Web">
    <meta name="keywords" content="Diseño web, pagina web, crear sitio web, una web">
    <meta name="copyright" content="T3D Design Company">
    <meta name="author" content="David A. Chentes">
    <meta name="audience" content="all">
    <meta name="description" content="Empresa de desarrollo y tecnologías web, una buena opción para todo el interesado en su presencia en línea">
    <meta name="robots" content="index, all, follow">
    <meta name="category" content="Diseño Web">  
    <meta name="telephone" content="+1 224 288 1535">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="" type="image/png" sizes="16x16">
    <title>{% block 'title' %}{% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block 'styles' %}{% endblock %}
</head>

<body class="" id="page-top">

    <header>
        <nav class="navbar color-nav shadow" data-bs-theme="warning">
            <div class="container-fluid">
                <div>
                <a class="navbar-brand" href="{% url "index" %}">Inicio</a>
                <a class="navbar-brand" href="{% url "sindicato" %}">Sindicato</a>
                <a class="navbar-brand" href="{% url "trabajadores" %}">Trabajador</a>
                <a class="navbar-brand" href="{% url "asambleas" %}">Asambleas</a>
                <a class="navbar-brand" href="{% url "map" %}">Map</a>
                {% if user.is_superuser %}<a class="navbar-brand" href="/admin">Admin</a>{% endif %}
                {% if user.is_authenticated %}
                        <a class="navbar-brand" href="{% url "logout" %}">Salir</a>
                {% endif %}
                </div>
                {% block search %}
                {% endblock search %}
            </div>
        </nav>          
    </header>

    <main>
        <ol class="breadcrumb mt-auto mb-auto">
            {% block breadcrumb %}{% endblock %}
        </ol>

        {% block 'content' %}{% endblock %}

    </main>

    <script src="{% static "js/main.js" %}"></script>
</body>
</html>